openapi: 3.0.0
info:
  title: Sleigh
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/andre4ik3/sleigh/blob/main/LICENSE'
  contact:
    name: andre4ik3
    email: andrey@andre4ik3.dev
servers:
  - url: 'http://localhost:8443'
paths:
  '/preflight/{machine_id}':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    post:
      summary: Get Preflight Config
      operationId: preflight
      responses:
        '200':
          description: Returns the config and a cookie.
          headers:
            Set-Cookie:
              schema:
                type: string
                format: uuid
              description: 'Contains a secure, same-site cookie with a random UUIDv4, set to expire in 60 seconds.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preflight-Config'
        '400':
          description: The data sent by the client is invalid or incomplete.
        '404':
          description: The data sent by the client didn't resolve to any config files.
      description: Returns the Preflight configuration and a cookie used later to identify the machine.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Preflight-Request'
          application/xml:
            schema:
              type: object
              properties: {}
        description: This data is automatically sent by all Santa clients.
      tags:
        - Santa
  '/ruledownload/{machine_id}':
    parameters:
      - schema:
          type: string
        name: machine_id
        in: path
        required: true
    post:
      summary: Get Rules
      operationId: post-ruledownload-machine_id
      responses:
        '200':
          description: Returns a list of rules.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rule'
        '400':
          description: This is returned when no cookie was sent by the client.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cursor:
                  type: integer
        description: 'No body is usually sent, unless the `batch_size` in the Preflight config matches the number of rules sent back. If so, a `cursor` is sent.'
      tags:
        - Santa
      description: Returns rules aggregated from the config files matching the `machine` cookie.
      parameters:
        - schema:
            type: string
            format: uuid
          in: cookie
          name: machine
          description: The machine UUID that temporarily identifies this machine for additional configuration.
          required: true
components:
  schemas:
    Preflight-Request:
      title: Client_Info
      type: object
      description: Contains the client information sent by Santa.
      properties:
        compiler_rule_count:
          type: integer
          example: 0
        client_mode:
          type: string
          example: MONITOR
        santa_version:
          type: string
          example: '2021.2'
        serial_num:
          type: string
        request_clean_sync:
          type: boolean
        hostname:
          type: string
          format: hostname
          example: andre4ik3.local
        binary_rule_count:
          type: integer
          example: 0
        primary_user:
          type: string
          example: andre4ik3
        certificate_rule_count:
          type: integer
          example: 0
        os_build:
          type: string
          example: 20D74
        transitive_rule_count:
          type: string
          example: '0'
        os_version:
          type: string
          example: 11.2.1
    Preflight-Config:
      title: Preflight-Config
      type: object
      description: Contains preflight configuration accepted by the Santa client.
      properties:
        client_mode:
          type: string
          example: MONITOR
        clean_sync:
          type: boolean
        batch_size:
          type: integer
        upload_logs_url:
          type: string
        allowed_path_regex:
          type: string
        blocked_path_regex:
          type: string
        full_sync_interval:
          type: integer
        fcm_token:
          type: string
        fcm_full_sync_interval:
          type: integer
        fcm_global_rule_sync_deadline:
          type: integer
        enable_bundles:
          type: boolean
        enable_transitive_rules:
          type: boolean
    Rule:
      title: Rule
      type: object
      description: A rule specifies what Santa should allow or block.
      properties:
        rule_type:
          type: string
          example: MONITOR
        policy:
          type: string
          example: ALLOWLIST
        sha256:
          type: string
        custom_msg:
          type: string
      required:
        - rule_type
        - policy
        - sha256
  securitySchemes: {}
tags:
  - name: Santa
