name: "Code Analysis"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  GraphQL:
    name: GraphQL Scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'python'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  OSSAR-Scan:
    name: OSSAR Scan
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout PR Head
      run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar

    - name: Upload OSSAR Results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}

  Flake8:
    name: "Flake8 Lint"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Flake8
      run: |
        python -m pip install -U pip
        python -m pip install -U flake8

    - name: Lint Code
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
