name: CI

on:
  push:
  pull_request:

jobs:
  init:
    name: Initialization
    runs-on: ubuntu-latest

    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check CI Skip Status
        id: ci-skip-step
        uses: mstachniuk/ci-skip@master

  lint:
    name: Flake8 Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Flake8
      run: |
        python -m pip install -U pip wheel
        python -m pip install -U flake8

    - name: Lint Code
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  format:
    name: Black Format
    needs: lint
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Black
        run: |
          python -m pip install -U pip wheel
          python -m pip install -U black

      - name: Check Format
        run: |
          black --check .
          echo "should_format=$?" >> $GITHUB_ENV
          exit 0

      - name: Reformat Code
        if: env.should_format == 1
        run: black .

      - name: Commit New Code (PR)
        if: env.should_format == 1 && github.event_name == 'pull_request'
        run: |
          git config --global user.name 'blackbot'
          git config --global user.email 'andre4ik3@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git pull
          git commit -am "[ci-skip] Reformat Code with Black"
          git push

      - name: Commit New Code (Push)
        if: env.should_format == 1 && github.event_name == 'push'
        run: |
          git config --global user.name 'blackbot'
          git config --global user.email 'andre4ik3@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git pull
          git commit -am "[ci-skip] Reformat Code with Black"
          git push origin HEAD:$GITHUB_REF

  scan-1:
    name: GraphQL Scan
    needs: [lint, init]
    if: needs.ci-skip.outputs.skip == 'false'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'python'
        setup-python-dependencies: false  # can't install uvloop for some reason

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  scan-2:
    name: OSSAR Scan
    needs: [lint, init]
    if: needs.ci-skip.outputs.skip == 'false'
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout PR Head
      run: git checkout HEAD^2
      if: github.event_name == 'pull_request'

    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar

    - name: Upload OSSAR Results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}

  python-test:
    name: Python Tests
    needs: [lint, init]
    if: needs.ci-skip.outputs.skip == 'false'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies & Pytest
      run: |
        python -m pip install -U pip wheel
        python -m pip install -U aiohttp ujson pytest pytest-aiohttp aiofiles

    - name: Run Tests
      run: |
        pytest sleigh/tests

  pypi-publish:
    name: PyPI Publish Package
    needs: [scan-1, scan-2, python-test, format]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Build Dependencies
      run: |
        python -m pip install -U pip wheel
        python -m pip install -U build twine -r requirements.txt

    - name: Build Distribution
      run: cd sleigh; python -m build

    - name: Upload Distribution
      run: python -m twine upload --username __token__ --password ${{ env.PYPI_TOKEN }} sleigh/dist/*

  docker-test:
    name: Docker Tests
    needs: [scan-1, scan-2, python-test, format]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  docker-push:
    name: Docker Push Container
    needs: [docker-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Image
        run: docker build . --file Dockerfile --tag sleigh

      - name: Get Ready to Push
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/sleigh

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag sleigh $IMAGE_ID:$VERSION

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push Image to GitHub Packages
        run: docker push $IMAGE_ID:$VERSION

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u andre4ik3 --password-stdin
  
      - name: Push Image to Docker
        run: docker push $IMAGE_ID:$VERSION
